logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
  file: logs/spring.log

server:
  port: ${PORT:8080}

spotify:
  base_url: https://api.spotify.com/

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE